### ISSUE TITLE
Problem with spaces

### ISSUE THREAD

**Issue by warpedsenses** [opennota/findimagedupes#4]
Gave it a try and liked it a lot, thanks!

Anyway, ran into some problems with filenames containing spaces, from what I gather you output the duplicates as:

path1<space>path2<newline>
...

Which gave me problems when I wanted to pipe the filenames to other programs, like mv/cp etc, because if the filenames have spaces, then I can't use the space as a delimiter, and if I use the newline as a delimiter, I will get two paths instead of one (and if the filenames have spaces I can't separate the two paths).

So is there any chance you could add an option that outputs each path followed by a newline ?

**Comment by opennota** [comment]
Well, the problem is that the output is not a single list but rather a list of lists. How useful would it be to have something like

```
img01.jpg\x00img01_cropped.jpg
i2.png\x00i3.jpeg\x00i4.jpg
DSC97766.JPG\x00z.jpg
```

(where \x00 represents zero byte) for three sets of duplicates?

But you can write a simple script and use it in the `-p` option. For example, let `copy.sh` be executable and contain
```
#!/bin/sh
cp "$@" /where-to-copy/
```

then you can call `findimagedupes` as

```
findimagedupes -p /path/to/copy.sh ~/Images
```

**Comment by opennota** [comment]
> So is there any chance you could add an option that outputs each path followed by a newline ?

In such a case all your sets of duplicates will be mixed up.

**Comment by warpedsenses** [comment]
Oh, your suggestion is a better solution, you can close this!
